- pom.xml
> Add vertx-health-check

- pom.xml
See https://github.com/vert-x3/vertx-cassandra-client/issues/11
> Added vertx-cassandra-client

- pom.xml
Signed-off-by: francesco <francescoguard@gmail.com>
> Added web-api-service to dependencies

- pom.xml
Follows-up on https://github.com/vert-x3/vertx-web/pull/1183
> Added Vert.x Web GraphQL

- pom.xml
https://github.com/eclipse-vertx/vertx-json-schema/issues/1
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
> Added vertx-json-schema

- pom.xml
This is needed in order to move forward with 
https://github.com/eclipse-vertx/vert.x/pull/3358
@vietj
> Add netty-codec-haproxy

- pom.xml
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
> Added vertx-web-validation

- pom.xml
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
> Added vertx-web-openapi

- pom.xml
For https://github.com/eclipse-vertx/vertx-sql-client/issues/696
> Add vertx-db2-client to dependencies

- pom.xml
> Invalid no longer built dependencies still referenced in dependencyManagement #51

- pom.xml
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
> Added vertx-opentelemetry

- pom.xml
Motivation:
Fix #61 
This is a redo of the PR #61 however I'm signing off this PR to adhere to the Eclipse Foundation requirements.
The PR also includes the CQ verifications:
* https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23492
* https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23491
* https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23490
> Update jackson to 2.11.4

- pom.xml
Motivation:
Adding new module `vertx-auth-otp`
> Adding vertx-auth-otp

- pom.xml
> Update to Netty 4.1.68.Final

- pom.xml
fixes https://github.com/netty/netty/security/advisories/GHSA-wx5j-54mm-rqqq
>  Update to netty 4.1.71.Final

- pom.xml
fixes https://github.com/netty/netty/security/advisories/GHSA-wx5j-54mm-rqqq
> Update to netty 4.1.71.Final

- pom.xml
Motivation:
https://netty.io/news/2022/02/08/4-1-74-Final.html
> Netty 4.1.74.Final upgrade

- pom.xml
> Bump jackson to avoid CVE

- pom.xml
> Backporting #87

- pom.xml
Motivation:
Update jackson to address CVEs
> Bumping jackson for addressing CVEs

- pom.xml
Motivation:
Update jackson BOM to ensure end users don't get the bad databind version.
> Bumping jackson to latest

- pom.xml
Reverts vert-x3/vertx-dependencies#121 for now.
> Revert "Upgrade to Netty 4.1.89.Final"

- pom.xml
See https://github.com/vert-x3/issues/issues/615
> Add new modules from vertx-launcher repo

- pom.xml
https://netty.io/news/2023/10/10/4-1-100-Final.html - fixes [CVE-2023-44487](https://nvd.nist.gov/vuln/detail/CVE-2023-44487)
> Upgrade to Netty 4.1.100.Final

- pom.xml
> Upgrade to Jackson 2.15.3

- pom.xml
fixes https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-29025
> Upgrade to Netty 4.1.108.Final

- pom.xml
> Update to Netty 4.1.115.Final.

- pom.xml
Motivation:
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:
Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines
> Upgrade to Netty 4.2.2
